[package]
name = "units-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = "4.1.3"
sha2 = "0.10.8"
rusqlite = { version = "0.30.0", features = ["bundled"] }
rocksdb = { version = "0.21.0", optional = true }
chrono = "0.4"

[dev-dependencies]
tempfile = "3.8"

[features]
default = ["sqlite"]
sqlite = []
rocksdb = ["dep:rocksdb"]
