[package]
name = "units-kernel-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = ["borsh/std"]